### ISSUE TITLE
Is it legal to link this library in a production build app ?

### ISSUE THREAD

**Issue by GHScan** [xrq-phys/blis_apple#1]
Dear developer, 

How about to use this library as an alternative to BNNS in production build? Will apple's reviewer reject my binary due to the use of AMX instruction? Is this project for research purpose only ?

Thanks

**Comment by xrq-phys** [comment]
Hi!

I'd say this work is basically for research purposes to test & benchmark Apple's matrix multiplication solution. Deploying it to scientific workloads (e.g. when they want to simulate quantum circuits with QFlux or do CAE with FreeFEM) if they want to run them on their own PC would also be well. But I generally advice against using this lib if you want to sell your software.

Legal issue is one thing, Apple has hundreds of reasons to reject software which exploits undocumented features because of "security concerns".

**Comment by GHScan** [comment]
Got it. It seems that I'd better keep using BNNS. 
Thank you for sharing this great work.
